[phases.setup]
nixPkgs = ["php83", "nginx", "nodejs_20"]

[phases.install]
cmds = [
    "npm install --prefix whatsapp",
    "npm install -g pm2",
    "mkdir -p /app/logs /app/uploads"
]

[phases.build]
cmds = ["mkdir -p /etc/nginx/conf.d"]

[start]
cmd = "/app/start.sh"

