[global]
error_log = /app/logs/php-fpm.log
daemonize = no

[www]
;user = nobody
;group = nobody
listen = 127.0.0.1:9000
pm = ondemand
pm.max_children = 5
pm.process_idle_timeout = 10s
pm.max_requests = 200
